/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * GameWindow.java
 *
 * Created on 2012-04-13, 13:05:35
 */
package memory.client;

import java.util.Vector;


/**
 *
 * @author blazej
 */
public class GameWindow extends javax.swing.JFrame {
    
    public static Vector<Card> deal = new Vector<Card>();
    private static int selected = 0;
    private static Card sCard1, sCard2;
    private static CardButt[] butts = new CardButt[30];
    

    /** Creates new form GameWindow */
    public GameWindow() {
        initComponents();
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Memory");
        setMinimumSize(new java.awt.Dimension(600, 600));

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 300));
        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel1.setText("jLabel1");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.EAST);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void uzupelnijKarty(){
        for (int i = 0; i < 30; i++){
            Card c = new Card(i, String.valueOf(MemoryClient.tablica[i]));
            deal.add(c);
        }
    }
    
    public void setLabelText(String text){
        this.jLabel1.setText(text);
    }
    
    public static void dodajWybor(Card karta){
        
        selected++;
        if (selected == 1) sCard1 = karta;
                
        System.out.println("selected wynosi: "+selected);
        if (selected == 2) {
            sCard2 = karta;
            if (Card.equal(sCard1, sCard2)){
                System.out.println("Parka!");
                sCard1.setTaken(true);
                sCard2.setTaken(true);
            }
            else {
                System.out.println("To nie jest parka");
            }
            selected = 0;
            try {
                Thread.sleep(2000);
            }
            catch (Exception ex){
                ex.printStackTrace();
            }
            for (Card c : deal){
                c.unreveal();
            }
            for (CardButt cb : butts){
                if (cb.cardTaken()){
                    cb.setEnabled(false);
                    cb.setSelected(true);
                }
                else {
                    cb.setEnabled(true);
                    cb.setSelected(false);
                }
                
            }
        }
    }
    
    public void wyswietlPrzyciski(int ilosc){
        
        jPanel1.setLayout(new java.awt.GridLayout(6, 5, 0, 0));
        
        for (int i = 0; i < 30; i++){
            butts[i] = new CardButt(deal.get(i));
            this.jPanel1.add(butts[i]);
        }  
    }
    
    private int getSelected(){
        return selected;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new GameWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
